### ISSUE TITLE
Support vscode remote ssh plugin

### ISSUE THREAD

**Issue by marlonfan** [wakatime/vscode-wakatime#105]
wakatime plugin show error status because used vscode remote ssh plugin.

vscode version: 1.35.0-insider (1.35.0-insider) 553cfb2c2205db5f15f3ee8395bbd5cf066d357d

wakatime plugin version: latest

**Comment by alanhamlett** [comment]
This is the [Remote SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) plugin? We currently support [Remote Development](https://code.visualstudio.com/docs/remote/remote-overview) through vscode Remote Workstations, but just opening remote files via ssh isn't yet supported since in that case the wakatime-cli client (Python) runs on your local machine and doesn't have access to the remote ssh file. Do you see an error in your `~/.wakatime.log` file with the prefix of `ssh://` saying the file wasn't found?

**Comment by marlonfan** [comment]
not found `~/.wakatime.log`.  and `Wakatime Initializing` always show at my status line

**Comment by marlonfan** [comment]
I found the cause of the problem because the HTTP proxy was used in my `setting.json`. but it doesn't  exists remote server.

that worked. thx!
