### ISSUE TITLE
24 hours of coding activity

### ISSUE THREAD

**Issue by DrummerSi** [wakatime/vscode-wakatime#106]
I get a lot of warnings telling me Wakatime has detected 24 hours of coding.

I believe this to be because I keep my workstation on 24/7 and I keep VSCode open. The plugin stops recording using the default 15 minute interval fine.. Unless it seems when the computer is locked (Win key + L).

Is this because the VSCode process is halted during this time? And when logged in again the plugin detects the last time it was working and the current time and thinks it's been working 48 hours over a weekend for example?

**Comment by alanhamlett** [comment]
> Is this because the VSCode process is halted during this time? And when logged in again the plugin detects the last time it was working and the current time and thinks it's been working 48 hours over a weekend for example?

No because the plugin only send heartbeats when a key is pressed or other similar editor events are triggered inside VSCode. Something about locking your machine must actually be causing an infinite loop of keypresses in VSCode, which triggers wakatime plugin heartbeat events continuously.

For ex: if you quit/close VSCode before locking your machine and it stops logging time, that proves it's something in VSCode causing editor keypress events while your machine is locked.

**Comment by gandarez** [comment]
Closing this issue due to the lack of activity, feel free to reopen @DrummerSi
