### ISSUE TITLE
Add/Update support for Sql Operations Studio -> Azure Data Studio For Mac

### ISSUE THREAD

**Issue by Ashtonian** [wakatime/vscode-wakatime#119]
The plugin page lists https://wakatime.com/sql-operations-studio plugin and I'm assuming its based on this one as the apps look like they share the same base. I think sql-operations-studio has been rebranded to 'azure data studio', I'm not sure if the plugin works with the newer versions of azure data studio on windows, but there is no wakatime plugin for it on mac and it looks to use the same codebase.

**Comment by Ashtonian** [comment]
I actually think its this fork that is listed on the site? https://github.com/Vaelek/vscode-wakatime

**Comment by Vaelek** [comment]
@Ashtonian - ADS support in Wakatime is poor at best. Partially because MS still hasn't figured out how to properly host ADS plugins separate from VSCode plugins. You don't want to use my fork, the activity queueing is not working and it will basically DOS the server with everything you do. If you download the vsix for the vscode version from the website, you can install it in ADS, but it will not log anything unless you are working on a saved sql file, which unless I'm abnormal, will almost never happen and renders the official version useless either way. I have seen zero progress on the ADS side of this plugin in the year or so since I found it, nor does the dev seem to care that their long since outdated installation guide is useless

**Comment by gandarez** [comment]
Also please comment in the PR to make sure they migrate as soon as possible. It's been taking a long time!

https://github.com/microsoft/azuredatastudio/pull/2182
