### ISSUE TITLE
wakatime-cli not updated

### ISSUE THREAD

**Issue by adhalanay** [wakatime/vscode-wakatime#171]
With the last version of wakatime extension I get the following messages in  the Debug window

`[Extension Host] [WakaTime][DEBUG] Current wakatime-cli version is 13.0.7`
`[Extension Host] [WakaTime][DEBUG] wakatime-cli is up to date`

While it should update wakatime-cli to version 13.1.0
About Vscode:

Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:16:10.374Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.0-1-amd64

**Comment by alanhamlett** [comment]
Current version released is 13.0.7 (https://wakatime-cli.s3-us-west-2.amazonaws.com/mac-x86-64/current_version.txt) because the Travis build broke recently:
https://travis-ci.org/github/wakatime/wakatime/builds/746118887

I'm wondering if it's worth fixing, since we're focusing all our efforts on the rewrite of wakatime-cli into Go.

**Comment by alanhamlett** [comment]
Fixed in v7.0.0 of the vscode extension, now that we're using the new [wakatime-cli](https://github.com/wakatime/wakatime-cli).
