### ISSUE TITLE
Not tracking time on Debian

### ISSUE THREAD

**Issue by Developer8814** [wakatime/vscode-wakatime#200]
Well i have wakatime with vscode in debian 10 buster, the extension never count the time and i never find the log file to see if i have a problem.

The extension not present a visual error or something.

**Comment by alanhamlett** [comment]
Any error message in your VS Code dev console or `~/.wakatime.log` file?

**Comment by Developer8814** [comment]
No, the extension only create a wakatime.cfg file.

i put wakatime in debug mode in vscode console still don't create the log file

**Comment by alanhamlett** [comment]
With debug mode, there should be some error messages in your VS Code Developer Console window?

**Comment by Developer8814** [comment]
The console says

[WakaTime][WARN] Failed to download https://wakatime-cli.s3-us-west-2.amazonaws.com/linux-x86-64/wakatime-cli.zip
S @ workbench.desktop.main.js:62
workbench.desktop.main.js:62 [Extension Host] [WakaTime][WARN] Error: unable to get local issuer certificate
S @ workbench.desktop.main.js:62
workbench.desktop.main.js:62 [Extension Host] [WakaTime][DEBUG] WakaTime: Initialized
workbench.desktop.main.js:62 [Extension Host] [WakaTime][DEBUG] Status bar icon enabled.

**Comment by alanhamlett** [comment]
What if you add this line to your `~/.wakatime.cfg` file then restart VS Code?

    legacy_python_cli = false

That downloads the core wakatime-cli from GitHub instead of AWS. Maybe something is preventing your vscode from connecting to AWS S3 for some reason.

**Comment by Developer8814** [comment]
Now, after the change the console says

[Extension Host] [WakaTime][DEBUG] Initializing WakaTime v10.0.0

and in the screen only say Wakatime Initializing .... and dont change

**Comment by alanhamlett** [comment]
That's strange... no errors and no more logs appear?

**Comment by Developer8814** [comment]
No, and the log file not exist.
![Captura de pantalla de 2021-05-21 12-59-19](https://user-images.githubusercontent.com/25228805/119179435-83f6fe00-ba34-11eb-9986-b54a63bfeeff.png)

![Captura de pantalla de 2021-05-21 12-56-38](https://user-images.githubusercontent.com/25228805/119179508-996c2800-ba34-11eb-9300-b8390bf52788.png)
![Captura de pantalla de 2021-05-21 12-56-22](https://user-images.githubusercontent.com/25228805/119179521-9e30dc00-ba34-11eb-8dea-0fe8f6f5c407.png)

**Comment by alanhamlett** [comment]
The plugin also can't connect to GitHub, so it's not able to initialize. Do you need a proxy to connect to the internet?

Also, I've invalidated your API Key since it should be secret but was shared here. You'll be asked to generate a new api key the next time you visit https://wakatime.com/dashboard.

**Comment by Developer8814** [comment]
Sorry i forgot to hide the Api Key, I already generated a new one.

No, i dont use a proxy to connect to the internet

**Comment by Developer8814** [comment]
After restart the computer for updates the wakatime extension initialized, but, no tracking the time

[WakaTime][WARN] GitHub API Response Error: Error: unable to get local issuer certificate
S @ workbench.desktop.main.js:62
workbench.desktop.main.js:62 [Extension Host] [WakaTime][DEBUG] WakaTime: Initialized
workbench.desktop.main.js:62 [Extension Host] [WakaTime][DEBUG] Status bar icon enabled.

**Comment by alanhamlett** [comment]
I'm not sure why, but the wakatime vscode plugin isn't able to connect to the internet to download wakatime-cli. You can get it working manually by downloading [wakatime-cli.zip](https://github.com/wakatime/wakatime-cli/releases/download/v1.7.3-alpha.2/wakatime-cli-linux-amd64.zip) (or [32bit version](https://github.com/wakatime/wakatime-cli/releases/download/v1.7.3-alpha.2/wakatime-cli-linux-386.zip) if you're not using 64bit linux) and then extracting that zip into `~/.wakatime/` so that there's a binary at `~/.wakatime/wakatime-cli-linux-amd64`.

**Comment by Developer8814** [comment]
Great!

Now the wakatime extension its working fine!

Thanks a lot for the support.

**Comment by alanhamlett** [comment]
You're welcome! I wish we could figure out why vscode can't make external network connections. That means you won't be getting new wakatime-cli updates since vscode can't connect to GitHub Releases.
