### ISSUE TITLE
Unable to install plugin in Azure Data Studio

### ISSUE THREAD

**Issue by alanrenmsft** [wakatime/vscode-wakatime#212]
redirected to here from Azure Data Studio, but the release it points to no longer exists.

**Comment by alanhamlett** [comment]
Looks like a bug in GitHub's website. Using the git command line I still see the tags for all the releases, even though the website says there aren't any tags:

```
git tag --list
...
v14.0.0
...
```

**Comment by alanhamlett** [comment]
There aren't any releases here, since this plugin is distributed via [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=WakaTime.vscode-wakatime) and available within your editor's CMD + P menu.

It should be the same for Azure Data Studio too?

**Comment by alanhamlett** [comment]
Just verified it works. Go to the extensions menu within Azure Data Studio, type `wakatime` in the search, click `Install`.

<img width="322" alt="Screen Shot 2021-07-13 at 9 40 10 PM" src="https://user-images.githubusercontent.com/522344/125562282-b5db3ffe-eea7-4187-8be3-03ba026db152.png">

**Comment by Charles-Gagnon** [comment]
@alanhamlett Did you click the Install button? It gives a 404 for me (because the link it's pointing to no longer exists, if it ever did) https://github.com/wakatime/vscode-wakatime/releases/tag/4.0.0

The ADS marketplace is different than the VS Code marketplace, we don't use the same system as they do and all 3rd party extensions are just links to pages to download the VSIX that the user can install manually.

I updated the link for WakaTime to point to https://marketplace.visualstudio.com/items?itemName=WakaTime.vscode-wakatime instead as that was the only place I could find that actually had the VSIX available for downloading. If you have a better suggestion for where to point it let us know.

**Comment by alanrenmsft** [comment]
@alanhamlett FYI, this is the original PR that adds the extension to ADS marketplace: https://github.com/microsoft/azuredatastudio/pull/11097/files#diff-2cfc66ce2bb5435f2d11ace11aec01380c27705a4c2ae005a26ed00d2ac585ecR3438

**Comment by gandarez** [comment]
Somehow all tags from the vscode repo has been deleted.

**Comment by alanhamlett** [comment]
> Did you click the Install button? It gives a 404 for me (because the link it's pointing to no longer exists, if it ever did)

Oh, I didn't. I had the extension already installed and just uninstalled it to get that screen shot.

> I updated the link for WakaTime to point to https://marketplace.visualstudio.com/items?itemName=WakaTime.vscode-wakatime instead as that was the only place I could find that actually had the VSIX available for downloading. If you have a better suggestion for where to point it let us know.

Let's use this link, since it's a direct download for the latest version as VSIX:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/WakaTime/vsextensions/vscode-wakatime/latest/vspackage

> Somehow all tags from the vscode repo has been deleted.

The `vsce` release tool only creates lightweight tags, so they don't show up in the GitHub tags page. I deleted the releases a while back because the last release on GH (v4.0.0) was very old. Sorry, I forgot ADS uses the releases page instead of the marketplace.

**Comment by Charles-Gagnon** [comment]
Thanks! 

https://github.com/microsoft/azuredatastudio/pull/16184

I updated it to point to version 14. Generally we shouldn't be just pointing to the latest release since we sometimes lag behind VS Code a bit and so if you push an updated version that depends on new APIs then that might break users. And because of the nature of our gallery the version displayed is hardcoded anyways so we can't really handle a version that can be freely updated.
