### ISSUE TITLE
failed to run command: sending heartbeat(s) later due to api error: won't send heartbeat due to backof

### ISSUE THREAD

**Issue by SCP-CN-001** [wakatime/vscode-wakatime#279]
Thank you for developing this nice plugin. Since about a month before, my vscode-wakatime frequently lose contact with the website. This week my plugin does not work anymore. I check the log file and it says

```{"caller":"cmd/run.go:276","func":"cmd.runCmd","level":"error","message":"failed to run command: sending heartbeat(s) later due to api error: invalid response status from \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\". got: 429, want: 201/202. body: \"{\\\"error\\\":\\\"Consuming heartbeats has been disabled for account [api-key].\\\"}\\n\"","now":"2022-06-10T00:06:43+08:00","version":"v1.48.1"}```

I checked that in the closed issues somebody has met a similar problem. I tried to downgrade my plugin but it does not work. Could you please help me to check what is wrong with my plugin?

**Comment by gandarez** [comment]
@alanhamlett

**Comment by alanhamlett** [comment]
`[api-key]` is actually your user id, no need to replace it in the log output since it's not secret. This rate limit error happens when you send more than 24hrs of continuous coding for a few days. What's your user id so I can reset your rate limiting for your account?

**Comment by SCP-CN-001** [comment]
Thank you for your help and reply! My user id/api-key is ```36e31fd4-965a-4bea-a47f-0ee6e357fe84```.

It is not my intention to trigger a wrong detection of 24hrs continuous coding. Is there any suggestion on the way to avoid the easily misunderstood operation?

**Comment by alanhamlett** [comment]
😨 `36e31fd4-965a-4bea-a47f-0ee6e357fe84` is your api key. I wasn't asking for your api key, I meant you don't need to manually sanitize your wakatime-cli logs because we never log your api key. Your api key is like a password to access your account, and you should keep it secret. Your user_id is different from your api key.

I've reset the rate limit for your account. Go to https://wakatime.com/ and you will be prompted to change your api key. Once you put that new api key inside vscode, your code time will show up on the dashboard.

**Comment by SCP-CN-001** [comment]
Thank you very much! I am able to sync my coding time again.
