### ISSUE TITLE
It says 'Error' in the status bar if no internet connectivity is found.

### ISSUE THREAD

**Issue by hashhar** [wakatime/vscode-wakatime#5]
It would be more helpful to add some other text like `No Internet` and a tooltip that says `We are still logging your work and will upload it as soon as we can find internet.`

If this behaviour is fine by you, I would like to work on it.

And hats off to you for almost single handedly managing the growing catalogue of wakatime plugins.

**Comment by alanhamlett** [comment]
Great idea. While we are at it, we should also add a new return code to [wakatime core](https://github.com/wakatime/wakatime) signaling an invalid api key. That way we can have two new warning messages:

* `Invalid api key`
* `Working offline, will sync activity after connecting`

Both mean coding activity is being saved while offline.

Then the third case can be an error message showing coding activity is not being saved, because of a bug in wakatime core.

**Comment by hashhar** [comment]
It means we have to first implement this status in the core. Then proceed and update all the plugins?

I'll try writing the new returns.

**Comment by alanhamlett** [comment]
Fixed with 71f0f1a1230edb494a8fcc8e3eec2a5bdb6bda3f and released in v1.0.3.
