### ISSUE TITLE
Python 100% CPU Usage

### ISSUE THREAD

**Issue by mikebronner** [wakatime/vscode-wakatime#74]
With WakaTime installed and enabled in VSCode Insiders build I get 100% CPU usage by Python. Running the following shows that it's the WakaTime plugin:

```
ps aux | grep 90303
mike             90303 100.0  0.4  4454664 118784   ??  R    11:23AM 186:43.74 pythonw /Users/mike/.vscode-insiders/extensions/wakatime.vscode-wakatime-1.2.5/out/wakatime-master/wakatime/cli.py --file /Users/mike/Developer/Sites/githelpdesk.com/public/js/app.js --plugin "vscode/1.31.0-insider vscode-wakatime/1.2.5" --alternate-project githelpdesk.com
mike              1190   0.0  0.0  4278276    828 s001  S+    2:30PM   0:00.00 grep --color=auto --exclude-dir=.bzr--exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 90303
```

<img width="598" alt="screen shot 2018-12-17 at 2 31 55 pm" src="https://user-images.githubusercontent.com/1791050/50119803-abfd2a00-0208-11e9-8bef-003b7c57700f.png">

**Comment by hurrtz** [comment]
This happens to me, too. I am running Visual Studio Code in Manjaro, which means that Visual Studio Code gets executed inside Electron. Maybe that's an issue? I'd be glad to supply more information if you like!

**Comment by gandarez** [comment]
@mikebronner @hurrtz try installing the latest version of WakaTime

**Comment by aka-tpayne** [comment]
I'm currently using v2.2.0/cli 13.0.0 and having this issue. Any suggestions?

**Comment by alanhamlett** [comment]
Can you turn on debug mode and watch your vscode console window? That shows every time the python cli process forks to send heartbeats, so I'm curious if it's forking once or many times. Also, does your process explorer show vscode or Python as using all the cpu?

**Comment by aka-tpayne** [comment]
So it seems to stem from clicking on a large file in the source control pane. The file is the built main.js which goes from ~400k (prod build) to 3.5MB (dev mode). Activity monitor shows Python. Process explorer shows this:
![image](https://user-images.githubusercontent.com/1674958/64032824-e39ad080-cb10-11e9-864d-af6d9fb572c5.png)

Here is the dev console:
![image](https://user-images.githubusercontent.com/1674958/64033189-8f442080-cb11-11e9-8e1d-7ac8d0c3cd53.png)

Here is a `ps aux | grep python`
![image](https://user-images.githubusercontent.com/1674958/64033385-fcf04c80-cb11-11e9-92bd-20ee430f6ffe.png)

I'm going to leave them running for now since it doesn't seem to cause many issues, in case you have other questions.
